FROM node:24-alpine3.21 AS build

WORKDIR /app

COPY package.json ./
COPY package-lock.json ./

RUN npm install

COPY . .

ARG VITE_API_BASE_URL_TEST
ENV VITE_API_BASE_URL=$VITE_API_BASE_URL_TEST

CMD ["npm", "test"]